### ISSUE TITLE
História: Apresentação dos Dados em Gráficos

### ISSUE THREAD

**Issue by GuilhermeGG12** [gabrielqr/web-saresp#18]
| Nome da História: | Apresentação dos dados em gráficos |
| :--- | :---|
| Como: |  Secretário de Educação |
| Eu gostaria de: | Ver os dados das escolas em gráficos |
| De forma que: | Eu possa visualizar os dados de cada escola de maneira facilitada |

Critérios de Aceitação: 
 - Os gráficos devem ser gerados a partir dos dados da SARESP.
 - Os gráficos devem ser feitos a partir de variáveis, como média geral, média por matéria, etc. 
 - Os gráficos devem ser de formatos variados, como linhas, barras, pizza, etc.

#19

**Comment by brenofranca83** [comment]
Evitem uso de listagens indefinidas nos critérios de aceite. Isso abre margem para aceitar qualquer coisa que apareça. Eles tem que ser objetivos.
