### ISSUE TITLE
História: Redução Automatizada do CSV para Apenas Dados Relevantes

### ISSUE THREAD

**Issue by GuilhermeGG12** [gabrielqr/web-saresp#23]
| Nome da História: | Redução Automatizada do CSV para Apenas Dados Relevantes |
| :--- | :--- |
| Como: | Desenvolvedor |
| Eu gostaria de: | Reduzir automaticamente o CSV para constar apenas dados relevantes |
| De forma que: | Eu possa otimizar o espaço de armazenamento e o tempo de processamento dos dados |

Critérios de Aceitação: 
 - A redução deve ser feita a partir de um arquivo CSV com dados do SARESP. 
 - A redução deve eliminar as colunas que não são usadas pelo web app.
 - A redução deve manter as colunas que são usadas pelo web app, como nome da escola, média, etc. 
 - A redução deve gerar um novo arquivo CSV com os dados reduzidos. 

#25

**Comment by brenofranca83** [comment]
Não existe história para o desenvolvedor... devem ser **apenas** do ponto de vista do usuário!
