### ISSUE TITLE
Feature: Importador de csv para Firestore database

### ISSUE THREAD

**Issue by gabrielqr** [gabrielqr/web-saresp#3]
Na seguinte feature precisamos transformar o csv padrão do site do saresp no csv que queremos e subir esses dados no firestore database (noSQL) do firebase.

**Comment by gabrielqr** [comment]
por ora, temos um código que transforma a csv que temos em uma csv com as seguintes colunas:

codRMet - number - id de região metropolitana (para comparações entre regiões)
CODESC - number - id de escola (talvez possa ser substituido por Id hash de cada escola)
NOMESC - string - nome escola 
SERIE_ANO - string - ano da escola (ex, 9º ano EF)
medprof - number - média

**Comment by gabrielqr** [comment]
ainda precisamos escrever o código de "importação", que é basicamente importar as linhas do csv para json (formato do firestore)

**Comment by gabrielqr** [comment]
### Dúvida: devemos subir as CSVs no repositório?

**Comment by gabrielqr** [comment]
@luizmgon, acabei de lembrar que temos que adicionar nos database alguma forma de saber o ano que é aquele dado

seŕa que é melhor separar (pra dps fazer consulta)

Escolas -> ano -> id escola -> chaves (média, serie, região metropolitana)
Escolas -> id escola -> chaves (Ano, média, série região metropolitana) ?

@Jesamin-30 ou @lattaro conseguem ajudar nisso?

**Comment by gabrielqr** [comment]
Agora o código está rodando e com as credenciais consigo subir o csv para o Firebase

Só que preciso sempre mudar o código para importar um csv. Provavelmente agora vou atualizar o código para pedir um input de nome de arquivo inicial e nome de arquivo final

**Comment by gabrielqr** [comment]
Estou implementando a credentials no github para que a gente não precise fazer o upload de forma manual.

**Comment by luizmgon** [comment]
Script para upload de arquivos .csv finalizado. Sempre que um novo .csv for adicionado à pasta "CSV Files" e upado no GitHub, um script é puxado pelo GitHub Actions para organização e upload deste arquivo no banco de dados (Firebase).
