### ISSUE TITLE
[ADD] Upar a primeira aplicação web

### ISSUE THREAD

**Issue by erickfelino** [gabrielqr/web-saresp#6]
Problemas:
A maior dificuldade no momento é conseguir vencer as politicas de privacidade existentes

Soluções
A ideia é construir botões básicos e conseguir realizar as primeiras ações, provavelmente usando firebase Hosting

Possibilidades
As alternativas ainda não estão sólidas, já que é uma base simples ainda

**Comment by gabrielqr** [comment]
**corrigido:**
Estava faltando a configuração do firebase hosting

**O que foi alterado**

- a pasta /front-end virou /public
- o html simple-button virou index.html (página inicial)
